apiVersion: nebulastream.com/v1
kind: NesTopology
metadata:
  name: 2-nodes
  annotations:
    topology-file-name: 2-nodes
spec:
  nodes:
    - name: worker1
      image: nebulastream/worker:distributed
      capacity: 0
      buffers: 10
      sinks:
        - name: fast_csv_sink
          type: Print
          config:
            inputFormat: CSV
    - name: worker2
      image: nebulastream/worker:distributed
      capacity: 0
      buffers: 10