apiVersion: nebulastream.com/v1
kind: NesTopology
metadata:
  name: edgeless-2
  annotations:
    topology-file-name: edgeless-2
spec:
  workerNodes:
    - host: worker-1
      image: nebulastream/worker:v2distributed
    - host: worker-2
      image: nebulastream/worker:v2distributed