apiVersion: nebulastream.com/v1
kind: NesTopology
metadata:
  name: edgeless-32
  annotations:
    topology-file-name: edgeless-32
spec:
  workerNodes:
    - host: worker-1
      image: nebulastream/worker:v2distributed
    - host: worker-2
      image: nebulastream/worker:v2distributed
    - host: worker-3
      image: nebulastream/worker:v2distributed
    - host: worker-4
      image: nebulastream/worker:v2distributed
    - host: worker-5
      image: nebulastream/worker:v2distributed
    - host: worker-6
      image: nebulastream/worker:v2distributed
    - host: worker-7
      image: nebulastream/worker:v2distributed
    - host: worker-8
      image: nebulastream/worker:v2distributed
    - host: worker-9
      image: nebulastream/worker:v2distributed
    - host: worker-10
      image: nebulastream/worker:v2distributed
    - host: worker-11
      image: nebulastream/worker:v2distributed
    - host: worker-12
      image: nebulastream/worker:v2distributed
    - host: worker-13
      image: nebulastream/worker:v2distributed
    - host: worker-14
      image: nebulastream/worker:v2distributed
    - host: worker-15
      image: nebulastream/worker:v2distributed
    - host: worker-16
      image: nebulastream/worker:v2distributed
    - host: worker-17
      image: nebulastream/worker:v2distributed
    - host: worker-18
      image: nebulastream/worker:v2distributed
    - host: worker-19
      image: nebulastream/worker:v2distributed
    - host: worker-20
      image: nebulastream/worker:v2distributed
    - host: worker-21
      image: nebulastream/worker:v2distributed
    - host: worker-22
      image: nebulastream/worker:v2distributed
    - host: worker-23
      image: nebulastream/worker:v2distributed
    - host: worker-24
      image: nebulastream/worker:v2distributed
    - host: worker-25
      image: nebulastream/worker:v2distributed
    - host: worker-26
      image: nebulastream/worker:v2distributed
    - host: worker-27
      image: nebulastream/worker:v2distributed
    - host: worker-28
      image: nebulastream/worker:v2distributed
    - host: worker-29
      image: nebulastream/worker:v2distributed
    - host: worker-30
      image: nebulastream/worker:v2distributed
    - host: worker-31
      image: nebulastream/worker:v2distributed
    - host: worker-32
      image: nebulastream/worker:v2distributed