apiVersion: nebulastream.com/v1
kind: NesTopology
metadata:
  name: edgeless-16
  annotations:
    topology-file-name: edgeless-16
spec:
  workerNodes:
    - host: worker-1
      image: nebulastream/worker:v2distributed
    - host: worker-2
      image: nebulastream/worker:v2distributed
    - host: worker-3
      image: nebulastream/worker:v2distributed
    - host: worker-4
      image: nebulastream/worker:v2distributed
    - host: worker-5
      image: nebulastream/worker:v2distributed
    - host: worker-6
      image: nebulastream/worker:v2distributed
    - host: worker-7
      image: nebulastream/worker:v2distributed
    - host: worker-8
      image: nebulastream/worker:v2distributed
    - host: worker-9
      image: nebulastream/worker:v2distributed
    - host: worker-10
      image: nebulastream/worker:v2distributed
    - host: worker-11
      image: nebulastream/worker:v2distributed
    - host: worker-12
      image: nebulastream/worker:v2distributed
    - host: worker-13
      image: nebulastream/worker:v2distributed
    - host: worker-14
      image: nebulastream/worker:v2distributed
    - host: worker-15
      image: nebulastream/worker:v2distributed
    - host: worker-16
      image: nebulastream/worker:v2distributed