apiVersion: nebulastream.com/v1
kind: NesTopology
metadata:
  name: edgeless-8
  annotations:
    topology-file-name: edgeless-8
spec:
  workerNodes:
    - host: worker-1
      image: nebulastream/worker:v2distributed
    - host: worker-2
      image: nebulastream/worker:v2distributed
    - host: worker-3
      image: nebulastream/worker:v2distributed
    - host: worker-4
      image: nebulastream/worker:v2distributed
    - host: worker-5
      image: nebulastream/worker:v2distributed
    - host: worker-6
      image: nebulastream/worker:v2distributed
    - host: worker-7
      image: nebulastream/worker:v2distributed
    - host: worker-8
      image: nebulastream/worker:v2distributed
