FROM sidondocker/nes-cli:nullable-patch

RUN apt-get update && apt-get install -y jq && rm -rf /var/lib/apt/lists/*

COPY src/main/java/org/acme/QueryReconciler/Utils/query-coordinator.sh /app/query-coordinator.sh
RUN chmod +x /app/query-coordinator.sh

ENTRYPOINT ["/app/query-coordinator.sh"]
CMD []