apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server
  template:
    metadata:
      labels:
        app: tcp-server
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-2
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-2
  template:
    metadata:
      labels:
        app: tcp-server-2
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-3
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-3
  template:
    metadata:
      labels:
        app: tcp-server-3
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-4
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-4
  template:
    metadata:
      labels:
        app: tcp-server-4
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-5
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-5
  template:
    metadata:
      labels:
        app: tcp-server-5
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-6
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-6
  template:
    metadata:
      labels:
        app: tcp-server-6
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-7
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-7
  template:
    metadata:
      labels:
        app: tcp-server-7
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-8
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-8
  template:
    metadata:
      labels:
        app: tcp-server-8
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-9
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-9
  template:
    metadata:
      labels:
        app: tcp-server-9
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-10
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-10
  template:
    metadata:
      labels:
        app: tcp-server-10
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-11
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-11
  template:
    metadata:
      labels:
        app: tcp-server-11
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-12
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-12
  template:
    metadata:
      labels:
        app: tcp-server-12
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-13
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-13
  template:
    metadata:
      labels:
        app: tcp-server-13
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-14
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-14
  template:
    metadata:
      labels:
        app: tcp-server-14
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-15
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-15
  template:
    metadata:
      labels:
        app: tcp-server-15
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-16
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-16
  template:
    metadata:
      labels:
        app: tcp-server-16
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-17
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-17
  template:
    metadata:
      labels:
        app: tcp-server-17
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-18
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-18
  template:
    metadata:
      labels:
        app: tcp-server-18
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-19
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-19
  template:
    metadata:
      labels:
        app: tcp-server-19
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-20
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-20
  template:
    metadata:
      labels:
        app: tcp-server-20
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-21
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-21
  template:
    metadata:
      labels:
        app: tcp-server-21
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-22
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-22
  template:
    metadata:
      labels:
        app: tcp-server-22
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-23
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-23
  template:
    metadata:
      labels:
        app: tcp-server-23
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-24
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-24
  template:
    metadata:
      labels:
        app: tcp-server-24
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-25
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-25
  template:
    metadata:
      labels:
        app: tcp-server-25
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-26
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-26
  template:
    metadata:
      labels:
        app: tcp-server-26
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-27
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-27
  template:
    metadata:
      labels:
        app: tcp-server-27
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-28
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-28
  template:
    metadata:
      labels:
        app: tcp-server-28
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-29
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-29
  template:
    metadata:
      labels:
        app: tcp-server-29
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-30
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-30
  template:
    metadata:
      labels:
        app: tcp-server-30
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-31
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-31
  template:
    metadata:
      labels:
        app: tcp-server-31
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-32
  labels:
    nes: server
spec:
  selector:
    matchLabels:
      app: tcp-server-32
  template:
    metadata:
      labels:
        app: tcp-server-32
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999