apiVersion: nebulastream.com/v1
kind: NesTopology
metadata:
  name: star-2
  annotations:
    topology-file-name: star-2
spec:
  sinks:
    - name: fast_csv_sink
      type: Print
      config:
        inputFormat: CSV
      schema:
        - name: streamstream2$start
          dataType: UINT64
        - name: streamstream2$end
          dataType: UINT64
        - name: stream$id
          dataType: UINT64
      host: worker-1
  logicalSources:
    - name: stream
      schema:
        - dataType: UINT64
          name: id
        - dataType: UINT64
          name: value
        - dataType: UINT64
          name: timestamp
    - name: stream2
      schema:
        - dataType: UINT64
          name: id2
        - dataType: UINT64
          name: value
        - dataType: UINT64
          name: timestamp
  physicalSources:
    - logicalSource: stream
      host: worker-1
      parserConfig:
        type: CSV
      type: TCP
      sourceConfig:
        socketHost: tcp-server
        socketPort: 6666
        flushIntervalMS: 1
        socketType: SOCK_STREAM
        socketDomain: AF_INET
    - logicalSource: stream2
      host: worker-2
      parserConfig:
        type: CSV
      type: TCP
      sourceConfig:
        socketHost: tcp-server-2
        socketPort: 6666
        flushIntervalMS: 1
        socketType: SOCK_STREAM
        socketDomain: AF_INET
  workerNodes:
    - host: worker-1
      image: nebulastream/worker:v2distributed
      capacity: 100
      executionMode: INTERPRETER
    - host: worker-2
      image: nebulastream/worker:v2distributed
      capacity: 0
      executionMode: INTERPRETER
      downstreamNodes:
        - worker-1