apiVersion: nebulastream.com/v1
kind: NesTopology
metadata:
  name: star-8
  annotations:
    topology-file-name: star-8
spec:
  sinks:
    - name: fast_csv_sink
      type: Print
      config:
        inputFormat: CSV
      schema:
        - name: streamstream2stream3stream4stream5stream6stream7stream8$start
          dataType: UINT64
        - name: streamstream2stream3stream4stream5stream6stream7stream8$end
          dataType: UINT64
        - name: stream$id
          dataType: UINT64
      host: worker-1
  logicalSources:
    - name: stream
      schema:
        - dataType: UINT64
          name: id
        - dataType: UINT64
          name: value
        - dataType: UINT64
          name: timestamp
    - name: stream2
      schema:
        - dataType: UINT64
          name: id2
        - dataType: UINT64
          name: value
        - dataType: UINT64
          name: timestamp
    - name: stream3
      schema:
        - dataType: UINT64
          name: id3
        - dataType: UINT64
          name: value
        - dataType: UINT64
          name: timestamp
    - name: stream4
      schema:
        - dataType: UINT64
          name: id4
        - dataType: UINT64
          name: value
        - dataType: UINT64
          name: timestamp
    - name: stream5
      schema:
        - dataType: UINT64
          name: id5
        - dataType: UINT64
          name: value
        - dataType: UINT64
          name: timestamp
    - name: stream6
      schema:
        - dataType: UINT64
          name: id6
        - dataType: UINT64
          name: value
        - dataType: UINT64
          name: timestamp
    - name: stream7
      schema:
        - dataType: UINT64
          name: id7
        - dataType: UINT64
          name: value
        - dataType: UINT64
          name: timestamp
    - name: stream8
      schema:
        - dataType: UINT64
          name: id8
        - dataType: UINT64
          name: value
        - dataType: UINT64
          name: timestamp
  physicalSources:
    - logicalSource: stream
      host: worker-1
      parserConfig:
        type: CSV
      type: TCP
      sourceConfig:
        socketHost: tcp-server
        socketPort: 6666
        flushIntervalMS: 1
        socketType: SOCK_STREAM
        socketDomain: AF_INET
    - logicalSource: stream2
      host: worker-2
      parserConfig:
        type: CSV
      type: TCP
      sourceConfig:
        socketHost: tcp-server-2
        socketPort: 6666
        flushIntervalMS: 1
        socketType: SOCK_STREAM
        socketDomain: AF_INET
    - logicalSource: stream3
      host: worker-3
      parserConfig:
        type: CSV
      type: TCP
      sourceConfig:
        socketHost: tcp-server-3
        socketPort: 6666
        socketType: SOCK_STREAM
        flushIntervalMS: 1
        socketDomain: AF_INET
    - logicalSource: stream4
      host: worker-4
      parserConfig:
        type: CSV
      type: TCP
      sourceConfig:
        socketHost: tcp-server-4
        socketPort: 6666
        flushIntervalMS: 1
        socketType: SOCK_STREAM
        socketDomain: AF_INET
    - logicalSource: stream5
      host: worker-5
      parserConfig:
        type: CSV
      type: TCP
      sourceConfig:
        socketHost: tcp-server-5
        socketPort: 6666
        flushIntervalMS: 1
        socketType: SOCK_STREAM
        socketDomain: AF_INET
    - logicalSource: stream6
      host: worker-6
      parserConfig:
        type: CSV
      type: TCP
      sourceConfig:
        socketHost: tcp-server-6
        socketPort: 6666
        socketType: SOCK_STREAM
        flushIntervalMS: 1
        socketDomain: AF_INET
    - logicalSource: stream7
      host: worker-7
      parserConfig:
        type: CSV
      type: TCP
      sourceConfig:
        socketHost: tcp-server-7
        socketPort: 6666
        socketType: SOCK_STREAM
        flushIntervalMS: 1
        socketDomain: AF_INET
    - logicalSource: stream8
      host: worker-8
      parserConfig:
        type: CSV
      type: TCP
      sourceConfig:
        socketHost: tcp-server-8
        socketPort: 6666
        socketType: SOCK_STREAM
        flushIntervalMS: 1
        socketDomain: AF_INET
  workerNodes:
    - host: worker-1
      image: nebulastream/worker:v2distributed
      capacity: 100
      worker.defaultQueryExecution.executionMode: INTERPRETER
    - host: worker-2
      image: nebulastream/worker:v2distributed
      downstreamNodes:
        - worker-1
      capacity: 0
      worker.defaultQueryExecution.executionMode: INTERPRETER
    - host: worker-3
      image: nebulastream/worker:v2distributed
      downstreamNodes:
        - worker-1
      capacity: 0
      worker.defaultQueryExecution.executionMode: INTERPRETER
    - host: worker-4
      image: nebulastream/worker:v2distributed
      downstreamNodes:
        - worker-1
      capacity: 0
      worker.defaultQueryExecution.executionMode: INTERPRETER
    - host: worker-5
      image: nebulastream/worker:v2distributed
      downstreamNodes:
        - worker-1
      capacity: 0
      worker.defaultQueryExecution.executionMode: INTERPRETER
    - host: worker-6
      image: nebulastream/worker:v2distributed
      downstreamNodes:
        - worker-1
      capacity: 0
      worker.defaultQueryExecution.executionMode: INTERPRETER
    - host: worker-7
      image: nebulastream/worker:v2distributed
      downstreamNodes:
        - worker-1
      capacity: 0
      worker.defaultQueryExecution.executionMode: INTERPRETER
    - host: worker-8
      image: nebulastream/worker:v2distributed
      downstreamNodes:
        - worker-1
      capacity: 0
      worker.defaultQueryExecution.executionMode: INTERPRETER