apiVersion: nebulastream.com/v1
kind: NesTopology
metadata:
  name: star-2
  annotations:
    topology-file-name: star-2
spec:
  logical:
    - name: stream
      schema:
        - type: UINT64
          name: id
        - type: UINT64
          name: value
        - type: UINT64
          name: timestamp
    - name: stream2
      schema:
        - type: UINT64
          name: id2
        - type: UINT64
          name: value
        - type: UINT64
          name: timestamp
  nodes:
    - name: worker1
      image: nebulastream/worker:distributed
      capacity: 100
      compilerExecutionMode: INTERPRETER
      sinks:
        - name: fast_csv_sink
          type: Print
          config:
            inputFormat: CSV
        - name: slow_csv_sink
          type: Print
          config:
            inputFormat: CSV
      physical:
        - logical: stream
          parserConfig:
            type: CSV
          sourceConfig:
            socketHost: tcp-server
            socketPort: 6666
            type: TCP
            socketType: SOCK_STREAM
            socketDomain: AF_INET
            flushIntervalMS: 1
    - name: worker2
      image: nebulastream/worker:distributed
      capacity: 0
      compilerExecutionMode: INTERPRETER
      links:
        downstreams:
          - worker1
      physical:
        - logical: stream2
          parserConfig:
            type: CSV
          sourceConfig:
            socketHost: tcp-server-2
            socketPort: 6666
            type: TCP
            socketType: SOCK_STREAM
            socketDomain: AF_INET
            flushIntervalMS: 1