apiVersion: v1
kind: Pod
metadata:
  name: systest-simulator-pod
spec:
  containers:
    - name: systest-simulator
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: stream-files-pvc
