apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-upstream-to-downstream
spec:
  podSelector:
    matchLabels:
      app: downstream
  policyTypes:
    - Ingress
  ingress:
    - {}