apiVersion: nebulastream.com/v1
kind: NesTopology
metadata:
  name: test-topology
spec:
  workerSpecs:
    - name: "upstream"
      image: "sidondocker/sender:latest"
      args: []
    - name: "downstream"
      image: "sidondocker/receiver:latest"
      args: []
