apiVersion: nebulastream.com/v1
kind: NesTopology
metadata:
  name: test-topology
spec:
  workerSpecs:
    - name: "worker1"
      image: "nebulastream/worker:nightly"
      args:
        - "--worker.bufferSizeInBytes=1"
    - name: "worker2"
      image: "nebulastream/worker:nightly"
      args: