apiVersion: v1
kind: Pod
metadata:
  name: nebuli-queries-reader
spec:
  containers:
    - name: nebuli-queries-reader
      image: busybox
      command: [ "sleep", "infinity" ]
      volumeMounts:
        - name: queries-volume
          mountPath: /tmp
  volumes:
    - name: queries-volume
      persistentVolumeClaim:
        claimName: queries-pvc
  restartPolicy: Always
