apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-server
  template:
    metadata:
      name: tcp-server
      labels:
        app: tcp-server
    spec:
      containers:
        - name: tcp-server
          image: sidondocker/tcp-server:latest
          ports:
            - containerPort: 6666