apiVersion: v1
kind: ServiceAccount
metadata:
  name: nes-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nes-operator-role
rules:
  - apiGroups: [ "nebulastream.com" ]
    resources:
      - "nes-topologies"
      - "nes-queries"
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources:
      - "pods"
      - "services"
      - "configmaps"
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "apps" ]
    resources:
      - "deployments"
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "batch" ]
    resources:
      - jobs
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nes-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nes-operator-role
subjects:
  - kind: ServiceAccount
    name: nes-operator
    namespace: default
